MP_API_KEY:
  api_key: LLD0JpDhyQM5SG5kH1DP76FLVpx1C5IG
codes:
  MatterGen:
    code_string: MatterGen@rosi_gpua100 #MatterGen@otus_gpu
    path_to_pretrained_models_csp: /bigdata/casus/fwuk/mirho50/pretrained_models/MatterGenCSP
    #/pc2/groups/hpc-prf-nniap/hossein/pretrained_models/MatterGenCSP  #/bigdata/casus/fwuk/mirho50/pretrained_models/MatterGenCSP
    model_name: chemical_system_energy_above_hull
    job_script:
      device: cuda
      nodes: 1
      ntasks: 1
      cpus: 8
      ngpu: 1
      time: 21600 #in s
      exclusive: False
  MatterSim:
    code_string: MatterSim@rosi_gpua100 #MatterSim@otus_gpu
    path_to_pretrained_models: /bigdata/casus/fwuk/mirho50/pretrained_models
    #/pc2/groups/hpc-prf-nniap/hossein/pretrained_models #/bigdata/casus/fwuk/mirho50/pretrained_models
    pretrained_model: mattersim-v1.0.0-5M.pth
    job_script:
      device: cuda
      nodes: 1
      ntasks: 1
      cpus: 12
      ngpu: 1
      time: 21600 #in s
      exclusive: False
  MACE:
    code_string: MACE@otus_gpu
    path_to_pretrained_models: /pc2/groups/hpc-prf-nniap/hossein/pretrained_models #/bigdata/casus/fwuk/mirho50/pretrained_models
    pretrained_model: MACE-matpes-pbe-omat-ft.model
    job_script:
      device: cuda
      nodes: 1
      ntasks: 1
      cpus: 12
      ngpu: 1
      time: 21600 #in s
      exclusive: False
  MinimaHopping:
    code_string: run_aiida_python@rosi_gpua100 #MH@otus_gpu
    job_script:
      device: cuda
      nodes: 1
      ntasks: 1
      cpus: 12
      ngpu:
      time: 21600 #in s
      exclusive: False
  VASP:
    code_string: VASP.6.4.2@noctua2n
    job_script:
      PBE:
        nodes: 1
        ntasks: 64
        cpus: 
        ngpu:
        time: 3600 #in s
        exclusive: False
      PBE_slab:
        nodes: 1
        ntasks: 64
        cpus: 
        ngpu:
        time: 3600 #in s
        exclusive: False
      r2SCAN:
        nodes: 1
        ntasks: 64
        cpus: 
        ngpu:
        time: 21600 #in s
        exclusive: False
      HSE:
        nodes: 2
        ntasks: 64
        cpus: 2
        ngpu:
        time: 36000 #in s
        exclusive: False
